spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_card?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.carddemo.model
server:
  port: 8080
